version: "3"

services:
    db:
        # M1 processor require platfor
        platform: linux/x86_64
        # image: mysql:latest
        build: ./mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database_name
            - MYSQL_CHARSET=utf8mb4
            - MYSQL_COLLATION=utf8mb4_general_ci
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ../db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            - PMA_HOST=db
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 8080:80

    api:
        build: ./api
        container_name: api
        restart: always
        volumes:
            - ./api/:/app
        environment:
            - FLASK_APP=/src/run.py
            - FLASK_SECRET_KEY='flask_secret_key'
            - MYSQL_HOST=db
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DB=database_name
            - MYSQL_CURSORCLASS=DictCursor
            - DEBUG=1
        expose:
            - 9000

    # ui:
    #   build: ./ui
    #   container_name: ui
    #   restart: always
    #   expose:
    #     - 80

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - ../log:/var/log/nginx/
        ports:
            - "8000:8000"
            - "8001:80"
